### ISSUE TITLE
How to customize?

### ISSUE THREAD

**Issue by helmut72** [cronicle-edge/cronicle-edge#111]
I want to re-install my cronicle-edge installation and playing on a 2nd machine. I took the default config.json, changed or added custom options and add config.json to my compose like this:

```
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config.json:/opt/cronicle/conf/config.json
      (...)
```

When starting cronicle, only settings will be used from config.json, that are not there in this configuration:

<img width="482" alt="Bildschirmfoto 2024-05-02 um 22 36 58" src="https://github.com/cronicle-edge/cronicle-edge/assets/1388751/649cf17f-4565-44b9-bd4b-6fdb74a66882">

For example, `email_from` is not used from my config.json, because it's there in this "22 keys". It will be only used, if I delete the default `email_from` manually in the webui. Not a good practice to automate first setup. Otherwise my custom `mail_options` are used, because it is not included in these "22 keys".

What is the right way to use my custom settings? Why can't I see my own additions in the graphical ui? It's only visible when opening "config viewer".

It would be really cool to prepare custom settings in environment variables like this:
https://github.com/go-gitea/gitea/blob/main/contrib/environment-to-ini/README

Thanks!

**Comment by mikeTWC1984** [comment]
Yeah, it's how it works. Those "Config Keys" let you dynamically overwrite your config.json at runtime. So it's not the same thing as config.json. Those are stored in storage engine, and you cannot use it to overwrite storage and server settings.
 I  put some common configs in setup.json  so user can see what they can tweak. Perhaps I'd need to remove it from there to avoid confusion. For now you can remove or overwrite it.

You can overwrite any configuration using env variable. It should start with with CRONICLE_ prefix, and for nested properties you need to use __ instead of .  It's original cronicle feature. You can even set storage and server setting. But those custom configs have higher priority

**Comment by helmut72** [comment]
Thank you. Never looked into setup.json and also thank you for clarify configuration via env variables.

But it looks like setup.json does have also priority over env variables!? When starting the container with `CRONICLE_email_from=test@test.com`, `email_from` is still `admin@cronicle.com`. Until I manually delete it from the webui.

> But those custom configs have higher priority

With custom settings you mean **your** custom config in `setup.json` and not **my** custom config via env variables?

> Perhaps I'd need to remove it from there to avoid confusion.

Or it should be highlighted on top of readme.md. I never saw this behavior in other Docker images. Do you know other Docker images, that ignore values in env variables (if this properties are supported of course)?

env variables should always overwrite default values.

**Comment by mikeTWC1984** [comment]
Sorry for confusion. Setup.json is just a file that init's the storage (on the very first run), so it enters "General" category, master groups, etc, including those 22 config keys.
Again, the fact that those 22 items take priority is a feature, not a bug. It wouldn't make any sense otherwise. It plays a role of "Setting" menu which can be changed later as needed without restarting cronicle or modifying the file. I loaded some common configs just to show them up. We can add an option not to load them on set up.

**Comment by helmut72** [comment]
You are right. This confused me lot that env vars are supported, but a few of them doesn't work as expected ;-)

Goal is a first start with my prefered settings without any manual interaction, then adding/removing cronjobs only via API, if other projects need a cronjob. Webui is just for reading what's going on or manual firing existing cronjobs, but not for changes.

Make it sense to use my own setup.json or is this a bad idea for future updates?

**Comment by mikeTWC1984** [comment]
No, keep setup.json as is. Or just remove lines related to config keys. For now just remove those conflicting items, I'll make them optional on the next release

**Comment by mikeTWC1984** [comment]
OK,  if using version 1.9.3, you can set variable CRONICLE_setup=minimal  in your docker files to skip loading most of those keys on setup.

**Comment by helmut72** [comment]
Looks good now, my URLs and SMTP settings are used and it even works with env vars :) Thanks for this fix and answering my questions!

To have the basic installation completely automatically, admin password and a first API need to be set via env vars or secrets, since my goal is using Cronicle via API only. But I guess this impossible?
