### ISSUE TITLE
No Python runtime environment

### ISSUE THREAD

**Issue by iferencz** [cronicle-edge/cronicle-edge#113]
# Shell Script

![](https://i.imgur.com/V1svazm.png)

# Error

![](https://i.imgur.com/FDowAHK.png)

I deploy Cronicle Edge using the following command

```
docker run -it -d --name cronicle-edge \
	-p 3012:3012 \
	cronicle/edge \
	manager
```

It seems that the error is reported because the Python operating environment does not exist.

In addition, this image has a Python operating environment: [https://github.com/bluet/docker-cronicle-docker/pull/19](https://github.com/bluet/docker-cronicle-docker/pull/19). But I don't know how to install Python libraries.Because it doesn't seem to have pip3.

How to install the Python running environment and its libraries in cronicle-edge. Thank you so much.

**Comment by mikeTWC1984** [comment]
Those images are using alpine, so you can install python and pip using this command
```apk add python3 py3-pip```

Perhaps alpine is not the greatest choice for python since it can use native dependencies that are not built for alpine. You might my also need to install "alpine-sdk" if pip need to build packages. 

Normally I'd suggest to prepare a docker image with the frameworks/software  you  need, then install cronicle on top of it. You can use Dockerfile file on this repo as an example.
