### ISSUE TITLE
This API call can only be invoked on the manager server.

### ISSUE THREAD

**Issue by dheise-rheinenergie-trading-com** [cronicle-edge/cronicle-edge#12]
Hi Mike,

Since friday, I'm running your fork behind a load balancer who distributes all requests my 3 servers behind. Some api calls are now rejected because they are not executed on the manager/master server. The original cronicle doesn't seems to have this problem. I think this version automatically redirects the api calls to the master. Could you also implement such a redirect?

Daniel

**Comment by mikeTWC1984** [comment]
Since you are saying some, can you list those endpoints/apis that are not working as you expect?
Some api do master check indeed. 

Are all those 3 nodes master nodes (have access to storage)?

**Comment by dheise-rheinenergie-trading-com** [comment]
All 3 servers have potentially have access to the data storage which is saved on a central NAS, but they are currently not in the master group.
I mainly use the api calls: get_schedule and run_event.

**Comment by mikeTWC1984** [comment]
Interesting. As far as I understand cronicle **run_event** can only be invoked on master:
https://github.com/jhuckaby/Cronicle/blob/6c268899870f48e048597f2847b719433320cf89/lib/api/event.js#L345

I guess most of apis should run on master only because  you need at least to check permissions (which requires access to storage). Probably your workers somehow treated as masters. I quite sure if you unmount data folder on your workers you won't be able to invoke any api on them

**Comment by dheise-rheinenergie-trading-com** [comment]
thanks for the clarification. I reconfigured my load balancer, so that all requests are delivered to my current master. Only if this system is down, all requests are sent to my backup/slave system.
