### ISSUE TITLE
Issue with Handling Socket Timeout in URL Plugin

### ISSUE THREAD

**Issue by Aub-C** [cronicle-edge/cronicle-edge#120]
QUESTION:
I'm using the URL Plugin for Cronicle, and my job is timing out with the error message: Error: Socket Timeout (80000 ms). I want this timeout to be considered a success because the job is completing on the backend without returning a response. I've tried multiple patterns and setting the SuccessMatch field to:

`(Success.*|Error: Socket Timeout \(80000 ms\))`

However, the job still fails. Can you confirm if this regex pattern is correct for matching the timeout error? If there are any additional steps or adjustments needed to properly handle this scenario, please advise. Am I understanding what the SuccessMatch field does correctly?

```
Error: Socket Timeout (80000 ms)
 
Request Headers:
User-Agent: Cronicle/1.0

Socket Timeout (80000 ms)

Performance Metrics: scale=1000&total=80127.317&dns=69.744&connect=5.128&send=18.689

**Comment by mikeTWC1984** [comment]
So that pattern applies to response body, not to error message.
https://github.com/jhuckaby/Cronicle/blob/master/docs/Plugins.md#built-in-http-request-plugin

E.g. cronicle rest api call always has 200 code, and just prints error message in the body. So you can add "Invalid API Key"  in Error regex to treat it as error.
