### ISSUE TITLE
Timed out jobs don't count as 'Failure' for chain reactions 

### ISSUE THREAD

**Issue by pedrotiag0** [cronicle-edge/cronicle-edge#152]
## Summary

Whenever a job is timed out, it should be logged as 'failed' and the associated chain reaction (if applicable) should be executed. Currently, it is only marked as 'failed' and nothing happens regarding the chain reaction.

## Steps to reproduce the problem

1. Create any job that gets timed out. Could be just a `sleep 120` sample script with a one minute timeout.
2. Assign any job as a "Run event as failure" chain reaction.
![image](https://github.com/user-attachments/assets/515bd02d-02bf-4e00-becc-a5f4e28190f2)
3. Validate that the associated chain reaction is not executed whenever the job is executed and timed out.

**Comment by mikeTWC1984** [comment]
@pedrotiag0  This is technically by design. When timeout occurs it invokes job abortion, same mechanism that you would use for manual job abortion. In  this case you typically want prevent any chain reaction.  The most common scenario to illustrate need for this behavior  is self-chained jobs. If abortion would trigger "failure"   you won't have an option to stop it (other than restarting cronicle). I guess in any other case when you initiating abortion, you'd prefer to stop chaining.
 I agree that timeout and manual abortion are a bit different scenarios.  Not sure if we need "2nd kind of abortion", perhaps we do, I'll think about it.
Technically you can initiate timeout internally from script, e.g. try set shebang this way
#!/usr/bin/env -S timeout 10  /usr/bin/bash

Should be fairly simple to do this on plugin level too

**Comment by pedrotiag0** [comment]
Thank you for the answer @mikeTWC1984 

It's a little misleading, since the job is tagged as "Failed" instead of something like "Timed out". Anyway, as you said there's other ways to address this "issue" be it by a plugin or a simple change to the shebang.
