### ISSUE TITLE
The write output does not show the errors

### ISSUE THREAD

**Issue by aolle99** [cronicle-edge/cronicle-edge#35]
Making a plugin in python, I have found that if you send error messages, it detects them as success anyway.
`print('{ "complete": 1, "code": 999, "description": "Failed to execute." }')`
This returns a success with the description Failed to execute.

**Comment by mikeTWC1984** [comment]
Just tried below, and getting correct completion
```python
#!/usr/bin/python3

print(" test plugin")
print('{ "complete": 1, "code": 999, "description": "Failed to execute." }')
```

![image](https://user-images.githubusercontent.com/31977106/183973362-8fbd4d0e-8bf1-44a9-9608-470d50d28e5e.png)

You might need to review your plugin. Looks like you print "complete:1, code:0" somewhere else. Otherwise you'd see some error like "exited without reporting completion"

**Comment by aolle99** [comment]
Thank you very much, the error came from what you mentioned
